### ISSUE TITLE
No LICENSE found

### ISSUE THREAD

**Issue by JacksonChen666** [cozybear-dev/uptime-checkor#1]
This project does not seem to have a license declared in an obvious way, or at all. A license should be added (as this project seems to be intended as open source) so that users can run, modify, study, distribute, and use the code.

https://choosealicense.com/no-permission/

**Comment by cozybear-dev** [comment]
Thank you for the reminder. Added GNU GPLv3 license.

**Comment by cozybear-dev** [comment]
See; https://github.com/cozybear-dev/uptime-checkor/commit/324b8ecaf87b685ecea868a693026a773cf1fa12

**Comment by JacksonChen666** [comment]
@cozybear-dev You need to have the [entire license terms](https://choosealicense.com/licenses/gpl-3.0/) in the file named "LICENSE" (or "COPYING" or whatever, i don't know). The notice in https://github.com/cozybear-dev/uptime-checkor/commit/324b8ecaf87b685ecea868a693026a773cf1fa12 should be applied to source code, not where the terms of the license should be.

**Comment by cozybear-dev** [comment]
@JacksonChen666 So like this https://github.com/cozybear-dev/uptime-checkor/commit/3c7b164a03f9005f9f592a9bccb387978ca4c93c?

**Comment by JacksonChen666** [comment]
@cozybear-dev Yep!
